#!/usr/bin/env python3
"""Play the finish-gate demo in a throwaway project and print docs/demo.md.

The commands are the ones an agent runs; every output line is SAKO's own. Paths,
dates, times and the date part of markers are normalized so the page is stable;
test_release.py checks that docs/demo.md still matches a fresh run.

    PYTHONDONTWRITEBYTECODE=1 python3 tests/demo.py > docs/demo.md
"""
from pathlib import Path
import json
import re
import subprocess
import sys
import tempfile

import selftest as fixture

ENV = dict(fixture.ENV, GIT_AUTHOR_DATE="2026-01-15T09:30:00+0000", GIT_COMMITTER_DATE="2026-01-15T09:30:00+0000")
INTRO = """# Demo: the finish gate

A transcript of a real run, generated by
[demo.py](../tests/demo.py) in a throwaway project; a test checks that this page
still matches a fresh run. The commands are the ones an agent types, the hook
lines are what Claude Code runs for it, and every output line is SAKO's own.
Paths, dates and times are normalized. It is a scripted run, not a recording of
an agent's judgment.

The story: the agent says it is done before it recorded its work, the gate
refuses and names the fix, the agent fixes the task and its check, closes it with a
receipt, commits, and a fresh session picks up the next task from the files.
"""


class Demo:
    def __init__(self, root: Path):
        self.root, self.lines = root, [INTRO]

    def normalize(self, text: str) -> str:
        text = text.replace(str(self.root.parent), "/work").replace(str(fixture.SAKO), "../sako/sako.py")
        text = re.sub(r"\bsk-\d{4}-", "sk-0115-", text)
        text = re.sub(r"\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d[+-]\d{4}", "2026-01-15T09:30:00+0000", text)
        text = re.sub(r"\d{4}-\d\d-\d\d \d\d:\d\d", "2026-01-15 09:30", text)
        text = re.sub(r"closed \d{4}-\d\d-\d\d", "closed 2026-01-15", text)
        return re.sub(r"(PASS in|after) \d+s", r"\1 0s", text)

    def say(self, text: str) -> None:
        self.lines.append(text)

    def run(self, shown: str, args: list[str], stdin: str | None = None, expect: int = 0) -> str:
        result = subprocess.run(args, cwd=self.root, env=ENV, input=stdin, capture_output=True, text=True)
        output = (result.stdout + result.stderr).rstrip()
        if result.returncode != expect:
            raise SystemExit(f"{shown}: exit {result.returncode}, expected {expect}\n{output}")
        exit_note = f"\n(exit {result.returncode})" if result.returncode or shown.startswith("#") else ""
        self.say("```text\n$ " + shown + ("\n" + self.normalize(output) if output else "") + exit_note + "\n```")
        return output

    def sako(self, *args: str, expect: int = 0) -> str:
        return self.run("python3 .sako/sako.py " + " ".join(f'"{a}"' if " " in a else a for a in args),
                        [sys.executable, ".sako/sako.py", *args], expect=expect)

    def hook(self, event: str, session: str, expect: int = 0) -> str:
        payload = json.dumps({"session_id": session, "hook_event_name": event})
        return self.run(f"# Claude Code's {event} hook ({session})", [sys.executable, ".sako/sako.py", "hook", "claude"],
                        stdin=payload, expect=expect)

    def git(self, *args: str) -> None:
        self.run("git " + " ".join(f'"{a}"' if " " in a else a for a in args), ["git", *args])


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="sako-demo-") as workspace:
        root = Path(workspace) / "greeting"
        root.mkdir()
        fixture.git(root, "init", "-q", "-b", "main")
        fixture.write(root, {"CLAUDE.md": "# Greeting\nA command-line greeting for a named visitor.\n",
                             "greeting.py": "import sys\nprint('Hello')\n",
                             "check.py": "import subprocess, sys\nout = subprocess.run([sys.executable, 'greeting.py', "
                             "'Ada'], capture_output=True, text=True).stdout.strip()\nif out != 'Hello, Ada!':\n"
                             "    sys.exit(f'expected Hello, Ada! but got {out}')\nprint('greeting check passed')\n"})
        subprocess.run(["git", "add", "-A"], cwd=root, env=ENV, check=True)
        subprocess.run(["git", "commit", "-qm", "A greeting"], cwd=root, env=ENV, check=True)
        demo, agent = Demo(root), fixture.fake_agent()
        ENV["SAKO_AGENT_PID"] = str(agent)
        try:
            demo.say("## 1. Install\n\nIn the project, with no flags. The project has a `CLAUDE.md`, so Claude Code "
                     "gets the hooks.")
            demo.run("python3 ../sako/sako.py init", [sys.executable, str(fixture.SAKO), "init"])
            fixture.write(root, {".sako/config.json": json.dumps({"verify_command": [sys.executable, "check.py"],
                                                                  "verify_paths": []})})
            demo.say("The check is the project's own `check.py`, set in `.sako/config.json` as "
                     "`\"verify_command\": [\"python3\", \"check.py\"]`.\n\n"
                     "## 2. The agent says it is done too early\n\nA session starts; the hook gives the agent its "
                     "context. The owner asks for a greeting by name, and the agent records the task.")
            demo.hook("SessionStart", "demo-agent")
            demo.sako("add", "A named visitor gets a personal greeting", "--done-when",
                      "python3 greeting.py Ada prints Hello, Ada!", "--scope", "greeting.py")
            fixture.write(root, {"greeting.py": "import sys\nprint(f'Hello {sys.argv[1]}')\n"})
            demo.say("The agent edits `greeting.py` but never claims the task, then tries to stop. The gate "
                     "refuses; exit 2 keeps the session going and shows the agent the message.")
            demo.hook("Stop", "demo-agent", expect=2)
            demo.say("## 3. The agent fixes it\n\nIt claims the task and runs the check, which fails: the "
                     "output lacks the comma and the exclamation mark.")
            demo.sako("claim", "T-1", "--session", "demo-agent")
            demo.sako("verify", expect=1)
            fixture.write(root, {"greeting.py": "import sys\nprint(f'Hello, {sys.argv[1]}!')\n"})
            demo.say("It fixes `greeting.py`, checks again, and closes the task with its evidence.")
            demo.sako("verify")
            demo.sako("close", "T-1", "--session", "demo-agent", "--evidence",
                      "greeting.py prints Hello, Ada!; check.py passes")
            demo.say("Stopping now is refused again: the work is closed but not committed.")
            demo.hook("Stop", "demo-agent", expect=2)
            demo.git("add", "--", "greeting.py")
            demo.git("commit", "-qm", "T-1: A named visitor gets a personal greeting")
            demo.say("Before leaving, the agent records the owner's next request. Now the gate is clear.")
            demo.sako("add", "An empty name gets a clear error", "--done-when",
                      "python3 greeting.py with no name prints Usage: greeting.py NAME", "--scope", "greeting.py")
            demo.hook("Stop", "demo-agent")
            demo.hook("SessionEnd", "demo-agent")
            demo.say("## 4. The receipt\n\nThe done record pairs the task's completion condition with the "
                     "evidence, the closing session, the date and what the check said.")
            demo.run("tail -1 .sako/work/DONE.md", ["tail", "-1", ".sako/work/DONE.md"])
            demo.say("## 5. A fresh session picks up\n\nA new conversation, with no chat history, gets the "
                     "records and the next task from the files.")
            demo.hook("SessionStart", "demo-next")
        finally:
            fixture.kill(agent)
        print("\n\n".join(demo.lines))


if __name__ == "__main__":
    main()
